## Chapter 3 - Exercise 1a: Thực hiện các yêu cầu sau, và đối chiếu với kết quả cho trước

In [43]:
import numpy as np

In [44]:
# Câu 1: Tạo numpy array có giá trị từ 0-9 và lưu vào biến arr
arr = np.arange(10)

# Hiển thị các phần tử có trong arr
print('arr:', arr)

# Xem kiểu dữ liệu (type) của arr
print('dtype of arr', arr.dtype)
print('type of arr', type(arr))

# Xem kích thước (shape) của arr
print('legnth of arr', arr.shape)

arr: [0 1 2 3 4 5 6 7 8 9]
dtype of arr int64
type of arr <class 'numpy.ndarray'>
legnth of arr (10,)


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[0 1 2 3 4 5 6 7 8 9]
&lt;class 'numpy.ndarray'&gt;
(10,)
</pre>
  
</details>

In [45]:
# Câu 2: Từ array arr ở câu 1 => tạo arr_odd và arr_even 

arr_odd = arr[arr % 2 != 0]
arr_even = arr[arr % 2 == 0]
# Hiển thị các phần tử có trong arr_odd và arr_even
print('arr_even:', arr_even)
print('arr_odd:', arr_odd)

arr_even: [0 2 4 6 8]
arr_odd: [1 3 5 7 9]


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>Odd array:
[1 3 5 7 9]
Event array:
[0 2 4 6 8]
</pre>
  
</details>

In [46]:
# Câu 3: Từ array arr ở câu 1=> tạo arr_update_1 với các phần tử chẵn giữ nguyên, các phần tử lẻ thay bằng 100
new_arr = np.array(arr)
print(arr)
new_arr[new_arr % 2 != 0] = 100

# Hiển thị các phần tử có trong arr_update_1
print(new_arr)

[0 1 2 3 4 5 6 7 8 9]
[  0 100   2 100   4 100   6 100   8 100]


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[  0 100   2 100   4 100   6 100   8 100]
</pre>
  
</details>