## Chapter 3 - Exercise 3: Thao tác trên mảng nhiều chiều, và đối chiếu với kết quả cho trước:

In [ ]:
import numpy as np

In [ ]:
# Câu 1: Tạo array arr có kích thước 3x3 với tất cả các giá trị đều là True. 

# Hiển thị các phần tử của array arr


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
</pre>
  
</details>

In [ ]:
# Câu 2: Cho array arr_1D = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8]). 

# Hãy chuyển thành array 2 chiều có kích thước 3x3 và lưu vào arr_2D.

# Xem danh sách các phần tử của arr_2D. 

# Trong arr_2D. Chuyển cột 1 sang cột 3 và ngược lại. => Xem lại danh sách các phần tử của arr_2D


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[0 1 2 3 4 5 6 7 8]
arr_2D: 
[[0 1 2]
 [3 4 5]
 [6 7 8]]
arr_2D sau khi chuyển cột: 
[[2 1 0]
 [5 4 3]
 [8 7 6]]
</pre>
  
</details>

In [ ]:
# Câu 3: Sử dụng array arr_2D của câu 2 (sau khi đổi thứ tự cột), chuyển dòng 1 sang dòng 2 và ngược lại 

# Xem lại danh sách các phần tử của arr_2D


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[[5 4 3]
 [2 1 0]
 [8 7 6]]
</pre>
  
</details>

In [ ]:
# Câu 4: Sử dụng array arr_2D của câu 3, Đảo ngược các dòng của array arr_2D 

# Xem lại danh sách các phần tử của arr_2D


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[[8 7 6]
 [2 1 0]
 [5 4 3]]
</pre>
  
</details>

In [ ]:
# Câu 5: Sử dụng array arr_2D của câu 4, Đảo ngược các cột của array arr_2D => Xem lại danh sách các phần tử của arr_2D


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[[6 7 8]
 [0 1 2]
 [3 4 5]]
</pre>
  
</details>

In [ ]:
# Câu 6: Cho arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]]),

# Kiểm tra xem trong array có giá trị rỗng nào không? 


<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>[[ 1.  2.  3.]
 [nan  5.  6.]
 [ 7. nan  9.]
 [ 4.  5.  6.]]
array có giá trị rỗng
</pre>
  
</details>

In [ ]:
# Câu 7: Sử dụng array arr_2D_null của câu 6, thay thế giá trị null bằng 0 => Xem lại danh sách các phần tử của arr_2D_null



<details>
  <summary>Nhấn vào đây để xem kết quả!</summary>
  <pre>Before:
[[ 1.  2.  3.]
 [nan  5.  6.]
 [ 7. nan  9.]
 [ 4.  5.  6.]]
After:
[[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
</pre>
  
</details>